### ISSUE TITLE
cargo build --release!

### ISSUE THREAD

**Issue by Samaneh14** [OceanGenomics/mudskipper#33]
cargo build --release running for Mudskipper installation get me the error, Your help to fix it is so appreciated!

error[E0308]: mismatched types
   --> src/annotation.rs:198:25
    |
198 |                 strand: exon_strand,
    |                         ^^^^^^^^^^^ expected enum `Strand`, found enum `bio_types::strand::Strand`
    |
    = note: perhaps two different versions of crate `bio_types` are being used?

For more information about this error, try `rustc --explain E0308`.
error: could not compile `mudskipper` due to previous error

**Comment by rob-p** [comment]
Hi @Samaneh14,

  Can you please say how you obtained Mudskipper and what version of rust you are using?  I just verified that a clean checkout from the `main` branch builds with several different recent versions of rust (e.g. 1.61.0).  This looks like it's an out-of-date dependency.  So definitely make sure your local dependencies are cleared out first with a `cargo clean`.

--Rob

**Comment by Samaneh14** [comment]
Hi Rob,

Thanks for your comment. I tried to install mudskipper through
git clone https://github.com/OceanGenomics/mudskipper
cd mudskipper
git show
cargo build --release

the rust version which I installed is rustc 1.63.0 (4b91a6ea7 2022-08-08) by 
curl --proto '=https' --tlsv1.3 https://sh.rustup.rs -sSf | sh

Also I loaded cmake CMake/3.16.1 in the cluster where I am trying to run mudskipper. 

I tried `cargo clean` and then `cargo build --release` to complete mudskipper installation, but it still doesn't work with that error. Should I install a special version of cmake? 

Thanks in advance!
Best regards,
Samaneh

**Comment by rob-p** [comment]
Hi Samaneh,

 Thanks!  Ok, so I can confirm that I'm able to reproduce this now.  Previously the `cargo.lock` file was preventing this from showing up.  This makes sense since it's related to a dependency.  Let me see if I can track down the problem.

--Rob

**Comment by rob-p** [comment]
Hi @Samaneh14,

  Ok, so I tried updating the version of `bio-types` in the dependencies and clearing out everything, and that seemed to help locally.  Can you please try the following:

```
cargo clean
rm cargo.lock
rm -fr target
git pull
cargo build --release
```

and let me know if that fixes the issue for you?

Thanks,
Rob

**Comment by Samaneh14** [comment]
Hi Rob,

Thank you so much for your time and the solution. It is fixed now and works well.

Best regards
Samaneh
