### ISSUE TITLE
Negative coordinate in output BAM

### ISSUE THREAD

**Issue by haghshenas** [OceanGenomics/mudskipper#8]
I have seen a case where the output BAM record has negative coordinate! Sample input BAM file is attached. For this test case, Mudskipper should be run using the following GTF.
```
http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_35/gencode.v35.annotation.gtf.gz
```

[sample bam file](https://github.com/OceanGenomics/mudskipper/files/7623600/test_negative_coordinate.zip)

**Comment by yfei-w** [comment]
After running the input bam file using: `mudskipper bulk`, the output bam file doesn't seem to have negative coordinates:

```
HWI-ST758:71:C06LWACXX:1:1101:1559:2137 16      ENST00000373316.5       1042    255     75M     *       0       0      GGTCCTGAAAGCAGCAAGAAGTATGCTGAGGCTGTCACTCGGGCTAAGCAGATTGTGTGGAATGGTCCTGTGGGG      ?=DDDEAE?;>EE=IECFAGF=FBFC888?B??B900:DFC??1?@G?4HCA?C:B??C:A:DA:A:A;D?????     NH:i:1  HI:i:1  AS:i:73 nM:i:0  NM:i:0
HWI-ST758:71:C06LWACXX:1:1101:1559:2137 16      ENST00000644362.1       981     255     75M     *       0       0      GGTCCTGAAAGCAGCAAGAAGTATGCTGAGGCTGTCACTCGGGCTAAGCAGATTGTGTGGAATGGTCCTGTGGGG      ?=DDDEAE?;>EE=IECFAGF=FBFC888?B??B900:DFC??1?@G?4HCA?C:B??C:A:DA:A:A;D?????     NH:i:1  HI:i:1  AS:i:73 nM:i:0  NM:i:0
```

Please let us know if you have more details, comments or test cases on this issue!
